### ISSUE TITLE
Logic determining which player to use is not robust

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#156]
The player is currently chosen based on the value of `state.url.includes('youtube')`.

It is entirely legitimate for a non-YouTube URL to contain the substring `youtube` (e.g., `http://example.com/videos-downloaded-from-youtube/video.mp4` or ``http://example.com/why-I-use-youtube.mp4``).

In such cases, the video will unexpectedly fail to load, and it will do so without providing a useful explanation to the end user.

This behavior is not what a user would expect after reading the documentation: the README says "Any **YouTube URL** uses the YouTube player", rather than "Any URL **containing 'youtube'** uses the YouTube player"

A better solution would be to test whether the **hostname** contains `youtube`. This can be extracted using:

```JavaScript
 new URL(state.url).hostname.includes('youtube')
```

However, I think the best solution is:

* load the YouTube player if the hostname is `youtube.com` or `www.youtube.com``, and the url has the correct format

* throw an error explaining the correct URL format if either the hostname is `youtube.com` or `www.youtube.com`` and the url has the incorrect structure, or the hostname is a different YouTube domain, 

* otherwise, load the HTML5 video player

**Comment by senakafdo** [comment]
@jamesscottbrown, it is not possible to accomodate your request since YouTube has variants that do not include ".com" in it. This is why we are testing for "youtube" in the URL. If there were other videos sourced from other URLs that have the words youtube in it, they can be re-written or hosted elsewhere unlike youtube videos which need to have that URL. This also has been [briefly explained in your PR](https://github.com/ove/ove-ui/pull/20).

**Comment by senakafdo** [comment]
I previously closed this
