### ISSUE TITLE
[Networks app] Example network does not render correctly

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#159]
The example named state `SigmaSample` defined in [config.json](https://github.com/ove/ove-apps/blob/master/packages/ove-app-networks/src/config.json) does not render correctly in the OVE Clients (but does render correctly in the controller).

**Comment by senakafdo** [comment]
This issue is not so easy to fix, as it seems. Perhaps we can document this in some way so that users will not be confused. Even when using the Les Misérables graph, it does not render in the visible area if the dimensions were something like 15360x4320. This is because Sigma assumes a canvas size proportional to the graph dimensions. This is regardless of whether `autoRescale` was set or not. However if the graph was specifically designed for such an aspect ratio and had corresponding (x, y) coordinates, it always renders properly.

I will anyway investigate further to see if this has anything to do with OVE's resizing logic.

**Comment by bcd00** [comment]
There is now a fix, where the UI launcher prevents users from opening the samples in a resolution higher than 2880x1616.

This appears to be an issue with the library being used, so an issue will be opened with them.

A description of this will be added to the documentation of the Networks app for if the user is using API calls and I will open an issue to provide a workaround, allowing the image to be displayed at 2880x1616 but utilising the full space.
