### ISSUE TITLE
[Videos App] YouTube Video Player is broken

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#170]
Playback of all YouTube videos is currently broken.

The YouTube player [prints a message indicating that it receives a youtube URL](https://github.com/ove/ove-apps/blob/master/packages/ove-app-videos/src/client/players/youtube.js#L23) including the video ID.

However ~~, this video ID never makes it into the `src` of the youtube element, and so the video never loads.~~  the `video_player` iframe remains `visible: none;`.

**Comment by senakafdo** [comment]
I would assume there has been some update to the Youtube iFrame API that has caused this behaviour.

Alternatively, it could also be due to the use of nginx LB that causes intermittent connection loss making it harder for websockets to maintain a steady stream of messages between them. The second can be tested and confirmed to be not to be the issue if attempted using a deployment that does not depend on nginx

**Comment by jamesscottbrown** [comment]
After enabling 'pausing on all exceptions' in the debugger on Chromium on my desktop I get a promising ratgetOrigin error message:

![error](https://user-images.githubusercontent.com/338833/57526934-9fe44700-7326-11e9-9130-9a01f80b2caf.png)

**Comment by senakafdo** [comment]
This may provide a clue, https://stackoverflow.com/questions/27573017/failed-to-execute-postmessage-on-domwindow-https-www-youtube-com-http.

**Comment by senakafdo** [comment]
According to further testing, it was observed that this is not an issue related to frame origins, but an issue related to the Youtube iFrame API, which no longer seems to be buffering the video if it is loaded within an iFrame with `display:none`. This use to be the case in the past, and is also the behaviour of the HTML5 video player provided by the browser, and seems to be an overnight change to the Youtube API, which we need to investigate further.
