### ISSUE TITLE
[Maps app] Support integration with Carto VL

### ISSUE THREAD

**Issue by miguems** [ove/ove-apps#42]
It would be great to fully support the connection to Carto's platform so we can leverage it. More info: 
[See more](https://carto.com/blog/carto-vl-vector-mapping-launch/)

**Comment by senakafdo** [comment]
@miguems, this looks super cool. Need to understand how this compares with OpenLayers and also whether it integrates with it at all. Ideally all apps should be like the videos app which supports the concept of more than one player, and we should be able to swap in/out the implementation software with ease, but a concept like a map is very much baked in.

**Comment by senakafdo** [comment]
@miguems, so I have read about this in depth. The Carto platform can be used with all popular OpenSource map-software. CartoVL works with Mapbox ([see example](https://carto.com/developers/carto-vl/examples/)), CARTO.js works with Leaflet ([see example](https://carto.com/developers/carto-js/v3/guides/getting-started/#leaflet-integration)) and OpenLayers also supports CartoDB natively ([see example](https://openlayers.org/en/latest/examples/cartodb.html)). 

I am assuming that your objective here is to support CartoDB rather than using CartoVL? Am I correct?

If so, I will test and document how to use this with OpenLayer, first and Leaflet (depending on whether we chose to proceed with #85) next.

**Comment by senakafdo** [comment]
I have had a look on how to use it with OpenLayers and it turns out to be very straightforward. See the state configuration below that has been tested on OVE 0.3.0. I will commit this into the source code and it will be available with the next release.

```json
{ 
  "type": "ol.layer.Tile",
  "visible": false,
  "wms": false,
  "source": {
    "type": "ol.source.CartoDB",
    "config": {
      "account": "documentation",
      "config": {
        "layers": [{
          "type": "cartodb",
          "options": {
            "cartocss_version": "2.1.1",
            "cartocss": "#layer { polygon-fill: #1E90FF; polygon-opacity: 0.6;}",
            "sql": "select * from european_countries_e where name = 'France'"
          }
        }]
      }
    }
  }
```

**Comment by senakafdo** [comment]
I'm resolving as this meets our requirements for using CartoDB as discussed offline. We will also need to introduce support for Carto maps when we introduce support for Leaflet in #85.
