### ISSUE TITLE
Code review for OVE Controller app

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#71]
As in #70, why not use a constant `MAX_ZOOM_LEVEL`, rather than hard-coding a value and explaining with a comment?

## package.json

1. As in #70, I don't think you need to depend on all of D3.

## src/client/control/controller.js

1. Why not use the [ove-core `getHostName()` function](https://github.com/ove/ove/blob/f2cd937f959252d2ff6987ed11d945e963525e20/packages/ove-core/src/client/ove.js#L16) [here](https://github.com/ove/ove-apps/blob/master/packages/ove-app-controller/src/client/control/controller.js#L67)?

1. There is currently an error check that tests whether `data.status === 400`, but what if a different error code is returned? It might be better to test for any 4xx or 5xx error code.

## src/client/view/controller.js

1. It looks like the minimum zoom level is 1, meaning that the user can zoom-in from the initial view, but cannot zoom out further thna the initial view. Is this correct? If so, why?

**Comment by senakafdo** [comment]
> Why not use the ove-core getHostName() function here?

OVE Core does not expose it and the computation is different.

> There is currently an error check that tests whether data.status === 400, but what if a different error code is returned? It might be better to test for any 4xx or 5xx error code.

The API documents that it only returns 400 errors.

> It looks like the minimum zoom level is 1, meaning that the user can zoom-in from the initial view, but cannot zoom out further thna the initial view. Is this correct? If so, why?

All apps let you zoom greater than the starting point. But, only some let you zoom below the starting point. But, may be we can get the min/max possible zoom levels using an API.

**Comment by senakafdo** [comment]
Resolving the issue along the lines of:
1. getHostname() related question cannot be addressed as the outcome of the two calls are different and OVE core does not need to expose two ways of getting the hostname, which also makes things complicated.
2. Testing for errors greater than 400, will solve the second issue but it could also lead to mistakenly treating data.status = 789 as a valid error state, which is incorrect. The current implementation much more accurate along those lines.
3. The requirement of an app computing min/max possible zoom levels does not seem to be practically possible since this is something computed by the app during runtime. If it is possible to compute zoom-levels, we can consider this as a feature improvement at a later point in time.
