### ISSUE TITLE
Code review for whiteboard app

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-apps#73]
## src/view/whiteboard.js

1. I would insert a newline [before the comment](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-whiteboard/src/client/view/whiteboard.js#L19) on line 19

2. The comment ["// Socket event listener"](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-whiteboard/src/client/view/whiteboard.js#L42) immediately above `window.ove.socket.on()` seems unneccessary

3. I'm not sure what is meant by the comment ["recursive redraw required"](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-whiteboard/src/client/view/whiteboard.js#L49). Where is the recursion?

## src/control/whiteboard.js

1. "The client" -> "Each client" in [this comment](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L19)

2. I would insert a newline before [this comment](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L68)

3. I'm also confused by [this comment](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L163) about "recusive redraw"

4. I'm not sure whether [returning if the filename is blank](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L304) is the correct action, or whether the user will expect the file to be downloaded with its default name instead. Pressing the cancel button causes `prompt()` to return `null` rather than `''`, so perhaps we should do:

```JavaScript

if (fileName === null){
	return;
}

fileName = fileName ? fileName : Constants.DEFAULT_FILE_NAME;

...

```

**Comment by senakafdo** [comment]
@jamesscottbrown, you perhaps were reading through the code when you reviewed it, compared to actually running it? The filename is blank if the user deletes the filename and leaves it blank. You cannot allow the download to pass it in that case as the browser will have other issues with your file. I don't think it makes sense to use the default filename in that case, because the prompt begins with the default filename, and if the user deletes it, that means they don't like it.

I cannot think of a better way to explain what the recursive redrawing is meant to be doing. It matches the process followed by the original draw operation. The drawOnCanvas method draws lines for all points in data.plots. When you keep calling it in a while loop providing it with a spliced list of data.plots, you will essentially be repeating the plotting over and over. The reason why this is required is to ensure we don't miss out on some points at some times, based on the rate at which events are fired and we pick them up.

**Comment by senakafdo** [comment]
So, I'm not going to change how saving works.

Use of pop vs splice is better. I have fixed it. The code was originally calling itself from within itself, and the while loop was introduced afterwards. Currently, it is an 'iterative' approach; agreed.

Codoodler and the whiteboard differ in their approach of capturing plots. As I have documented, it is only the UX that is common. And, also, I think your third point on on a user being confused is not relevant. This explains what the code does and does not concern any configuration that is available for a user.

Now, let me get to the actual code. Since there has been a lot of questions on this, I have had a second consideration at the code itself and whether it can be replaced or written in some other way. 

So, there are three instances of the same code being used.
1. [Within the draw operation](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L146)
2. When [restoring plots from history](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L165)
3. When [replicating the controller's operations on the viewer](https://github.com/ove/ove-apps/blob/c21d01a146fec3330572ffc61156804848cd47bb/packages/ove-app-whiteboard/src/client/view/whiteboard.js#L51).

The first is the actual operation and the two others simply replicate it. The [draw operation](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L113) allows someone to keep adding points to a list and then it paints the points while the draw operation is in progress. Codoodler does the same thing by calling [drawOnCanvas](https://github.com/pubnub/codoodler/blob/310bc6ea06d49bf0605238f118587591613959f5/js/app.js#L105) within the [draw](https://github.com/pubnub/codoodler/blob/310bc6ea06d49bf0605238f118587591613959f5/js/app.js#L96) operation. If you don't do this, either the lines would not be continuous or the end user will not see anyline until they have completed their drawing.

Since above is how the drawing happens, the two other operations (you don't find these in Codoodler as their usecase is not ours), need produce the same end result. I have updated the comment to explain this as well.

**Comment by jamesscottbrown** [comment]
Our disagreement is about whether or not the iteration is actually needed for the other two operations to produce the same result.

I repeat my earlier argument:

> on each subsequent iteration, the path that is drawn will entirely overlap the lines drawn at all previous iterations. How will this increase the thickness of the line that is drawn?

As a concrete example of this, look at [this JSFiddle](https://jsfiddle.net/5co60xtL/): both lines have the same thickness, despite the fact that one has been drawn once, and the over has been overdrawn 500 times.

**Comment by senakafdo** [comment]
You need to use a [better example](https://jsfiddle.net/jrpakot5/).

**Comment by jamesscottbrown** [comment]
Thanks for providing this modified example.

I now see what is going on: if you superimpose strokes, then their antialising does not work correctly. I had not anticipated this, and apparently it has [surprised other people too](https://stackoverflow.com/questions/12164780/html5-canvas-stroke-not-anti-aliased). The behaviour is repeatable across browsers (Safari, Chrome, and Firefox). How noticeable it is depends on the angle of the line.

In your modified example, the curve with the superimposed strokes is very jagged: the stroke that is drawn once looks *significantly* better.

This suggests an alternative implementation: within the draw function, draw a stroke that consists of a single line segment from where the previous stroke ended to the location of the new event point. In other words, draw only the new section of the stroke, rather than redrawing everything.

This could be done by calling

```JavaScript

let numPoints = context.plots.local.length;
drawOnCanvas(context.color, context.plots.local.slice(numPoints-2, numPoints));

```

[rather than](https://github.com/ove/ove-apps/blob/master/packages/ove-app-whiteboard/src/client/control/whiteboard.js#L146):

```JavaScript

drawOnCanvas(context.color, context.plots.local);

```

Then, if you remove the iteration in the other instances, the strokes will still look the same, but will look significantly better than they do now.

**Comment by senakafdo** [comment]
This is only possible if the numPoints that you get at each iteration is fixed or if you can assume that you can start redrawing the line at an intermediate previous point and get exactly the same output as if you had drawn the line continuously. This is not possible because of how the browser special cases lineJoin and lineCap, which will again lead to differences between the lines that are drawn.

The difference in the two lines that you see is not actually due to anti-aliasing or anything like that, but due to lineJoin and lineCap. See this [modified example](https://jsfiddle.net/8b5yhdp7/). You should notice the ending of the third line is different to that of the second. You can experiment by setting different types of lineJoin/lineCap along with different levels of redrawing to understand what I mean here.

**Comment by jamesscottbrown** [comment]
> The difference in the two lines that you see is not actually due to anti-aliasing or anything like that, but due to lineJoin and lineCap.
>....
> In other words, the amount of pixels occupied by each join/cap is what makes the line look jagged. 

I'm pretty sure that this is wrong, because there is noticeable difference in jaggedness along the length of a stroke that is a single line segment, not just near the endCap.

https://jsfiddle.net/L1fnzrqj/

**Comment by jamesscottbrown** [comment]
> fixed or if you can assume that you can start redrawing the line at an intermediate previous point and get exactly the same output as if you had drawn the line continuously. This is not possible because of how the browser special cases lineJoin and lineCap, which will again lead to differences between the lines that are drawn

With `lineCap` and `lineJoin` both set to `round`, I can't tell whether the results of drawing two strokes or an single stroke composed of two line segments are exactly the same, but they look at least Close Enough: https://jsfiddle.net/s1o6e5ug/1/

**Comment by jamesscottbrown** [comment]
I think we are talking at cross purposes - let's discuss this in person on Monday.

**Comment by senakafdo** [comment]
> I think we are talking at cross purposes - let's discuss this in person on Monday.

I think we would end up changing nothing, which is why I encouraged you to actually run and test the code in a comparable setting. But, I'm happy to discuss if you insist.

**Comment by senakafdo** [comment]
Also, @jamesscottbrown, ahead of our conversation on Monday. There is one important point you also should note, which I have not mentioned so far (sorry about that). This may also change your viewpoint completely.

When we originally draw something on the controller, we would draw a certain number of points at a time. This is not necessarily all the points in a single plot. The number of points on a single plot depends on when you started drawing and when you ended. The number of points available at each call to the draw operation is dependent on how frequently the browser decides to invoke the respective event handler. So, it could be one or it could be ten.

Now, when we broadcast the points to the viewers or save it in the plot history, we store it as a plot, but not as a series of draw events that were made. So, when we re-draw, we wouldn't know how many draw events it took to draw the plot in the first place. The over-plotting is designed to overcome the limitations of not knowing this.

There is not much of a performance loss due to over-plotting, though you may consider the operation to be not so well written code. However, there is a significant performance loss of broadcasting each individual draw event as it happens. This will impact both the source and the destination and it will also increase size and the processing overhead of the plot history.
